CREATE DATABASE Labo3dd2;
USE Labo3dd2;

CREATE TABLE VIAJE(
id_viaje INT  NOT NULL,
fecha DATE NOT NULL,
duracion INT NOT NULL,
matricula INT NOT NULL,
id_puerto_maritimo_origen int NOT NULL,
id_puerto_maritimo_destino int NOT NULL ,
id_capitan iNT NOT NULL,
);
CREATE TABLE PUERTOMARITIMO(
id_puertomaritimo INT  NOT NULL,
nombre VARCHAR(70) NOT NULL,
gps VARCHAR(70) NOT NULL,
id_ciudad INT ,
id_pais INT,
id_origen int,
id_destino int,
);
CREATE TABLE CIUDAD(
id_ciudad INT  NOT NULL,
ciudad VARCHAR(80) NOT NULL
);
CREATE TABLE PAIS(
id_pais INT  NOT NULL,
pais VARCHAR(80) NOT NULL
);
CREATE TABLE PASAJERO(
pasaporte int  NOT NULL,
nombre VARCHAR(100) not null,
fecha_nac DATE NOT NULL,
correo_electronico varchar(100) NOT NULL,
telefono INT NOT NULL,
id_pais INT NOT NULL
);
CREATE TABLE CAPITAN(
id_capitan int  NOT NULL,
nombre VARCHAR(100) NOT NULL
);
CREATE TABLE BARCO(
matricula INT  NOT NULL,
capacidad int NOT NULL,
id_modelo int NOT NULL
);
CREATE TABLE MODELO(
id_modelo int  NOT NULL,
modelo int NOT NULL,
id_fabricante INT NOT NULL
);
CREATE TABLE FABRICANTE(
id_fabricante int NOT NULL,
fabricante VARCHAR(50) NOT NULL
);
CREATE TABLE RESERVA(
id_reserva int NOT NULL,
precio MONEY NOT NULL,
fecha DATE not null,
id_tipocabina INT not null,
id_viaje INT NOT NULL,
pasaporte INT NOT NULL,
);
CREATE TABLE TIPOCABINA(
id_tipocabina INT NOT NULL,
tipocabina varchar(50) NOT NULL
);
CREATE TABLE SERVICIO(
id_servicio int NOT NULL,
nombre VARCHAR(50) NOT NULL,
precio MONEY NOT NULL
);
CREATE TABLE SERVICIOxRESERVA(
id_reserva int NOT NULL,
id_servicio int NOT NULL
)
--DECLARACION DE FK
ALTER TABLE VIAJE
ADD PRIMARY KEY(id_viaje);
ALTER TABLE VIAJE
ADD CONSTRAINT matriculaXViaje
FOREIGN KEY(matricula) REFERENCES BARCO(matricula)
ALTER TABLE VIAJE
ADD CONSTRAINT PUERTO_ORIGENXVIAJE
FOREIGN KEY(id_puertomaritimo_origen) REFERENCES PUERTO(id_puertomaritimo);
ALTER TABLE VIAJE 
ADD CONSTRAINT PUERTO_DESTINOxVIAJE
FOREIGN KEY(id_puertomaritimo) REFERENCES PUERTO(id_puertomaritimo);
ALTER TABLE VIAJE
ADD CONSTRAINT CAPITANxVIAJE
FOREIGN KEY (id_capitan) REFERENCES CAPITAN(id_capitan)
ALTER TABLE VIAJE 
ADD CONStRAINT VIAJEORIGEN
FOREIGN KEY(id_puerto_maritimo_origen) REFERENCES PUERTOMARITIMO(id_puertomaritimo);
ALTER TABLE VIAJE
ADD CONSTRAINT VIAJEDESTINO
FOREIGN KEY(id_puerto_maritimo_Destino) REFERENCES PUERTOMARITIMO(id_puertomaritimo)
--barco
ALTER TABLE BARCO
ADD PRIMARY KEY(MATRICULA);
ALTER TABLE BARCO 
ADD CONSTRAINT MODELOXBARCO
FOREIGN KEY(id_modelo) REFERENCES MODELO(id_modelo);
--MODELO
ALTER TABLE MODELO
ADD PRIMARY KEY(id_modelo);
ALTER TABLE MODELO
ADD CONSTRAINT MODELOXFABRICANTE
FOREIGN KEY(id_Fabricante) REFERENCES FABRICANTE(id_fabricante);
--FABRICANTE
ALTER TABLE FABRICANTE
ADD PRIMARY KEY(id_fabricante);
--CAPITAN 
ALTER TABLE CAPITAN
ADD PRIMARY KEY(id_capitan);
--CIUDAD
ALTER TABLE CIUDAD
ADD PRIMARY  KEY(id_ciudad);
--PAIS
ALTER TABLE PAIS
ADD PRIMARY KEY(id_pais);
--tipo CABINA
ALTER TABLE TIPOCABINA
ADD PRIMARY KEY(id_tipocabina);
--SERVICIO
ALTER TABLE SERVICIO
ADD PRIMARY KEY(id_servicio);
--PUERTO MARITIMO 
ALTER TABLE PUERTOMARITIMO
ADD PRIMARY KEY(id_puertomaritimo);
ALTER TABLE PUERTOMARITIMO
ADD CONSTRAINT CIUDADxPUERTO
FOREIGN KEY(id_ciudad) REFERENCES CIUDAD(id_ciudad);
ALTER TABLE PUERTOMARITIMO
ADD CONSTRAINT PAISXPUERTO
FOREIGN KEY(id_pais) REFERENCES PAIS(id_pais);
--pasajero
ALTER TABLE PASAJERO
ADD PRIMARY KEY(PASAPORTE);
ALTER TABLE PASAJERO
ADD CONSTRAINT PASAJEROXPAIS
FOREIGN KEY(id_pais) REFERENCES PAIS(ID_PAIS);
--reserva
ALTER TABLE RESERVA
ADD PRIMARY KEY(id_reserva);
ALTER TABLE RESERVA
ADD CONSTRAINT RESERVAxTIPOCABINA
FOREIGN KEY(id_tipocabina) REFERENCES TIPOCABINA(id_tipocabina);
ALTER TABLE RESERVA
ADD CONSTRAINT RESERVAXVIAJE
FOREIGN KEY(id_viaje) REFERENCES VIAJE(id_viaje);
ALTER TABLE RESERVA 
ADD CONSTRAINT PASAJEROXRESERVA
FOREIGN KEY(pasaporte) REFERENCES PASAJERO(pasaporte);
--reservaxtipo
ALTER TABLE SERVICIOXRESERVA
ADD CONSTRAINT SERVICIOXRESERVA
FOREIGN KEY(id_reserva) REFERENCES RESERVA(id_reserva);
ALTER TABLE SERVICIOXRESERVA
ADD CONSTRAINT SERVICIOXRESERVA2
FOREIGN KEY(id_servicio) REFERENCES SERVICIO(id_servicio)
ALTER TABLE SERVICIOXRESERVA
ADD PRIMARY KEY(id_servicio);
ALTER TABLE SERVICIOXRESERVA
ADD PRIMARY KEy(id_reserva);
--AGReGANDO DATOS
INSERT INTO CAPITAN(id_capitan,nombre)
VALUES(1,'PEDRO'),
(2,'JUAN'),
(3,'DIEGO'),
(4,'RENE'),
(5,'KELVIN');
INSERT INTO PAIS(id_pais,pais)
VALUES(1,'EL SALVADOR'),
(2,'GUATEMALA'),
(3,'VENEZUELA'),
(4,'BOLIVIA'),
(5,'SUDAFRICA');
INSERT INTO FABRICANTE(id_fabricante,fabricante)
VALUES(1,'MUSUN'),
(2,'NESTLE'),
(3,'APPLE'),
(4,'PEPSI'),
(5,'NINTENDO');
SELECT * FROM CAPITAN;
SELECT * FROM PAIS;
SELECT *FROM FABRICANTE;