CREATE DATABASE TALLER;
USE TALLER;

--creando tablas
CREATE TABLE ESCRITOR(
id	INT NOT NULL,
nombre VARCHAR(100) NOT NULL);
CREATE TABLE AUTOR(
id_escritor INT NOT NULL,
id_recurso INT NOT NULL);
CREATE TABLE RECURSO(
id INT NOT NULL,
titulo VARCHAR(100) NOT NULL,
descripcion VARCHAR(200) NOT NULL DEFAULT 'DESCRIPCION NO DISPONIBLE',
id_biblioteca INT NOT NULL,
id_coleccion INT NOT NULL,
id_pais INT NOT NULL);
CREATE TABLE BIBLIOTECA(
id INT NOT NULL,
nombre VARCHAR(100) NOT NULL,
horario CHAR(11) NOT NULL CHECK(horario LIKE '[0-9][0-9][:][0-9][0-9][-][0-9][0-9][:][0-9][0-9]'),
telefono CHAR(8) NOT NULL UNIQUE,
url_b VARCHAR(100) NULL);
CREATE TABLE EJEMPLAR(
id INT NOT NULL,
ubicacion VARCHAR(100) NOT NULL,
fecha_adquisicion DATE NULL,
id_recurso INT NOT NULL);
CREATE TABLE PRESTAMO(
id INT NOT NULL,
id_socio INT NOT NULL,
id_ejemplar INT NOT NULL,
fecha_prestamo DATE NOT NULL,
hora_prestamo CHAR NULL,
fecha_devolucion DATE NOT NULL CHECK(fecha_devolucion>=GETDATE()) );
CREATE TABLE SOCIO(
id INT NOT NULL,
nombre VARCHAR(100) NOT NULL,
correo_electronico VARCHAR(100) NOT NULL UNIQUE check (RIGHT(len(correo_electronico)-11,len(correo_electronico))='gmail.com'),
fotografia VARCHAR(100) NOT NULL DEFAULT 'NO DISPONIBLE',
direccion VARCHAR(100) NOT NULL,
telefono CHAR(8) NULL,
id_perfil INT NOT NULL);

CREATE TABLE PERFIL(
id INT NOT NULL,
titulo VARCHAR(100) NOT NULL,
descripcion VARCHAR(100) NOT NULL);
CREATE TABLE PAIS(
id INT NOT NULL,
nombre VARCHAR(30) NOT NULL);
CREATE TABLE COLECCION(
id INT NOT NULL,
titulo VARCHAR(100) NOT NULL);
CREATE TABLE ESTADO(
id INT NOT NULL,
titulo VARCHAR(100) NOT NULL,
descripcion VARCHAR(50) NOT NULL);
CREATE TABLE CONDICION(
id INT NOT NULL,
id_ejemplar INT NOT NULL,
id_estado INT NOT NULL,
fecha_inicio DATE NOT NULL,
fecha_fin DATE NOT NULL,
descripcion VARCHAR(200) NOT NULL);
CREATE TABLE RESERVA(
id INT NOT NULL,
id_socio INT NOT NULL,
id_ejemplar INT NOT NULL,);
--GENERANDO PK
ALTER TABLE BIBLIOTECA
ADD PRIMARY KEY(id);
ALTER TABLE ESCRITOR
ADD PRIMARY KEY(id);
ALTER TABLE AUTOR
ADD CONSTRAINT ESCRITORXRECURSO
PRIMARY KEY(id_escritor,id_recurso);
ALTER TABLE PAIS
ADD PRIMARY KEY(id);
ALTER TABLE COLECCION
ADD PRIMARY KEY(id);
ALTER TABLE RECURSO
ADD PRIMARY KEY(id);
ALTER TABLE ESTADO
ADD PRIMARY KEY(id)
ALTER TABLE EJEMPLAR
ADD PRIMARY KEY(id);
ALTER TABLE CONDICION
ADD PRIMARY KEY(id);
ALTER TABLE PRESTAMO
ADD PRIMARY KEY(id);
ALTER TABLE SOCIO
ADD PRIMARY KEY(id);
ALTER TABLE PERFIL
ADD PRIMARY KEY(id);
ALTER TABLE RESERVA
ADD PRIMARY KEY(id);
--AGREGANDO FOREIGN KEYS
ALTER TABLE AUTOR
ADD CONSTRAINT AUTORXESCRITOR
FOREIGN KEY(id_escritor) REFERENCES ESCRITOR(id);
ALTER TABLE AUTOR 
ADD CONSTRAINT AUTORXRECURSO
FOREIGN KEY(id_recurso) REFERENCES RECURSO(id);
ALTER TABLE RECURSO
ADD CONSTRAINT RECURSOXBIBLIOTECA
FOREIGN KEY(id_biblioteca) REFERENCES BIBLIOTECA(id);
ALTER TABLE RECURSO
ADD CONSTRAINT RECURSOXBPAIS
FOREIGN KEY(id_pais) REFERENCES PAIS(id);
ALTER TABLE RECURSO
ADD CONSTRAINT RECURSOXCOLECCION
FOREIGN KEY(id_coleccion) REFERENCES COLECCION(id);
ALTER TABLE EJEMPLAR 
ADD CONSTRAINT EJEMPLAXRECURSO
FOREIGN KEY(id_recurso) REFERENCES RECURSO(id);
ALTER TABLE PRESTAMO
ADD CONSTRAINT PRESTAMOXSOCIO
FOREIGN KEY(id_socio) REFERENCES SOCIO(id);
ALTER TABLE PRESTAMO
ADD CONSTRAINT PRESTAMOXEJEMPLAR
FOREIGN KEY(id_ejemplar) REFERENCES EJEMPLAR(id);
ALTER TABLE SOCIO 
ADD CONSTRAINT SOCIOXPERFIL
FOREIGN KEY(id_perfil) REFERENCES PERFIL(id);
ALTER TABLE CONDICION
ADD CONSTRAINT CONDICIONXEJEMPLAR
FOREIGN KEY(id_ejemplar) REFERENCES EJEMPLAR(id);
ALTER TABLE CONDICION
ADD CONSTRAINT CONDICIONXESTADO
FOREIGN KEY(id_estado) REFERENCES ESTADO(id);
ALTER TABLE RESERVA
ADD CONSTRAINT RESERVAXSOCIO
FOREIGN KEY(id_socio) REFERENCES SOCIO(id);
ALTER TABLE RESERVA
ADD CONSTRAINT RESERVAXEJEMPLAR
FOREIGN KEY(id_ejemplar) REFERENCES EJEMPLAR(id);
