CREATE DATABASE PRACTICA_CASA
--Creando tablas
USE PRACTICA_CASA;
CREATE TABLE PROYECTO(
codigo INT NOT NULL,
nombre VARCHAR(100) NOT NULL, 
presuespuesto MONEY NOT NULL DEFAULT 0.00,
id_coordinador int NOT NULL
);
CREATE TABLE EJECUCION(
id INT NOT NULL,
codigo_proyecto INT NOT NULL,
id_municipio INT NOT NULL CHECK(id_municipio>0 AND id_municipio<266),
fecha_inicio DATE NOT NULL CHECK(fecha_inicio>=GETDATE()),
fecha_fin DATE NOT NULL
)
CREATE TABLE MUNICIPIO(
id INT NOT NULL ,
nombre VARCHAR(100) NOT NULL,
);
CREATE TABLE ASIGNACION(
codigo_empleado INT NOT NULL,
codigo_proyecto INT NOT NULL
);
CREATE TABLE EMPLEADO(
codigo INT NOT NULL,
nombre VARCHAR(100) NOT NULL,
correo_electronico VARCHAR(100) NOT NULL,
numero_isss CHAR(7) NOT NULL CHECK (LEN(numero_isss) = 7 AND LEFT(numero_isss, 2) != '00'),
id_categoria INT NOT NULL
);
CREATE TABLE TELEFONO(
id INT NOT NULL,
numero INT NOT NULL,
codigo_empleado INT NOT NULL);
CREATE TABLE CATEGORIA(
id INT NOT NULL,
nombre VARCHAR(100) NOT NULL,
descripcion VARCHAR(200) NOT NULL,
);
CREATE TABLE OBJETIVO(
id INT NOT NULL,
titulo VARCHAR(100) NOT NULL,
descripcion VARCHAR(200) NOT NULL,
id_proyecto int NOT NULL);
CREATE TABLE METRICA(
id INT NOT NULL,
titulo VARCHAR(100) NOT NULL,
tipo_metrica VARCHAR(100) NOT NULL,
fecha_cumplimiento DATE NOT NULL,
id_objetivo int NOT NULL,
id_empleado INT NOT NULL);
--definiendo primary keys
ALTER TABLE PROYECTO 
ADD PRIMARY KEY(codigo);
ALTER TABLE EJECUCION
ADD PRIMARY KEY(id);
ALTER TABLE municipio
ADD PRIMARY KEY(id);
ALTER TABLE ASIGNACION
ADD CONSTRAINT SERVICIOxRESERVA
PRIMARY KEY(codigo_empleado,codigo_proyecto);
ALTER TABLE EMPLEADO
ADD PRIMARy KEY(codigo);
ALTER TABLE TELEFONO
ADD PRIMARY KEY(id);
ALTER TABLE CATEGORIA
ADD PRIMARY KEY(id);
ALTER TABLE OBJETIVO
ADD PRIMARY KEY(id);
ALTER TABLE METRICA
ADD PRIMARY KEY(id)
--agregando FK
ALTER TABLE PROYECTO
ADD CONSTRAINT PREYECTOxASIGNACION
FOREIGN KEY(id_coordinador) REFERENCES EMPLEADO(codigo);
ALTER TABLE ASIGNACION
ADD CONSTRAINT ASIGNACIONXEMPLEADO
FOREIGN KEY(codigo_empleado) REFERENCES EMPLEADO(codigo);
ALTER TABLE ASIGNACION
ADD CONSTRAINT ASIGNACIONXPROYECTO
FOREIGN KEY(codigo_proyecto) REFERENCES PROYECTO(codigo);
ALTER TABLE EMPLEADO
ADD CONSTRAINT EMPLEADOxCATEGORIA
FOREIGN KEY (id_Categoria) REFERENCES CATEGORIA(id);
ALTER TABLE TELEFONO
ADD CONSTRAINT TELEFONOXEMPLEADO
FOREIGN KEY(codigo_empleado) REFERENCES EMPLEADO(codigo);
ALTER TABLE EJECUCION
ADD CONSTRAINT EJECUCIONXPROYECTO
FOREIGN KEY(codigo_proyecto) REFERENCES PROYECTO(codigo);
ALTER TABLE EJECUCION
ADD CONSTRAINT EJECUCIONXMUNICIPIO
FOREIGN KEY(id_municipio) REFERENCES MUNICIPIO(id);
ALTER TABLE OBJETIVO
ADD CONSTRAINT OBJETIVOXPROYECTO
FOREIGN KEY(id_proyecto) REFERENCES PROYECTO(codigo);
ALTER TABLE METRICA
ADD CONSTRAINT METRICAXOBJETIVO
FOREIGN KEY(id_objetivo) REFERENCES OBJETIVO(id);
ALTER TABLE METRICA
ADD CONSTRAINT METRICAXEMPLEADO
FOREIGN KEY(id_empleado) REFERENCES EMPLEADO(codigo);

-- CREANDO VALIDACIONES
